name: Cron
on:
  workflow_dispatch:
  # schedule every monday at 10:00
  schedule:
    - cron: "0 10 * * 1"

permissions:
  contents: write
  id-token: write
  actions: write

jobs:
  scrape_and_create_menu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node & Npm
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Scrape Discounts
        run: npm run start
        env:
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
